
CREATE TABLE IF NOT EXISTS users (
	uid INTEGER PRIMARY KEY AUTOINCREMENT,
	user_name TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
	cid INTEGER PRIMARY KEY AUTOINCREMENT,
	course_code TEXT UNIQUE NOT NULL,
	creator INTEGER,
	date DATETIME DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (creator) REFERENCES users(uid) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS chapters (
	chid INTEGER PRIMARY KEY AUTOINCREMENT,
	cid INTEGER NOT NULL,
	chapter_name TEXT NOT NULL,
	UNIQUE (cid, chapter_name),

	FOREIGN KEY (cid) REFERENCES courses(cid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notes (
	nid INTEGER PRIMARY KEY AUTOINCREMENT,
	chid INTEGER,
	filename TEXT NOT NULL,

	mimetype TEXT NOT NULL CHECK (mimetype = 'application/pdf'),
	size INTEGER NOT NULL,
	data BLOB NOT NULL,

	creator INTEGER,
	status TEXT CHECK (status IN ('complete', 'incomplete')) DEFAULT 'incomplete',
	date DATETIME DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (chid) REFERENCES chapters(chid) ON DELETE CASCADE,
	FOREIGN KEY (creator) REFERENCES users(uid) ON DELETE SET NULL
);
